# -*- coding: utf-8 -*-
"""Inspirit AI Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Cx0ObBL7S-CynFE3vYuszXdLkOH5LBl
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded)))
df.head()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report

X = df[["Time_spent_Alone", "Stage_fear", "Social_event_attendance",
        "Going_outside", "Drained_after_socializing", "Friends_circle_size"]]
y = df["Personality"]

lex = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = lex.fit_transform(X[col].astype(str))

ley = LabelEncoder()
y_encoded = ley.fit_transform(y)

imputer = SimpleImputer(strategy="mean")
X_imputed = imputer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_imputed, y_encoded, test_size=0.33)

clf = LogisticRegression(max_iter=100)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=ley.classes_))

y_pred = clf.predict(X_train)

print("\nClassification Report:\n", classification_report(y_train, y_pred, target_names=ley.classes_))

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

randomForestModel = RandomForestClassifier(max_depth=4, n_estimators=100)
randomForestModel.fit(X_train, y_train)

y_pred_random_tree_test = randomForestModel.predict(X_test);

print(classification_report(y_test, y_pred_random_tree_test))


y_pred_random_tree_train = randomForestModel.predict(X_train);

print(classification_report(y_train, y_pred_random_tree_train))

from sklearn.neural_network import MLPClassifier

MLPModel = MLPClassifier(max_iter=300).fit(X_train, y_train)
MLPModel.fit(X_train, y_train)

y_pred_mlp_model_test = MLPModel.predict(X_test)

accuracy_MLP_model = classification_report(y_test, y_pred_mlp_model_test)
print(accuracy_MLP_model)



y_pred_mlp_model_train = MLPModel.predict(X_train)

print(classification_report(y_train, y_pred_mlp_model_train))

from sklearn.tree import DecisionTreeClassifier

decisionTreeModel = DecisionTreeClassifier(max_depth = 12)
decisionTreeModel.fit(X_train, y_train)

y_pred_tree_test = decisionTreeModel.predict(X_test)

accuracy_tree_classifier = classification_report(y_test, y_pred_tree_test)
print(accuracy_tree_classifier)

y_pred_tree_test = decisionTreeModel.predict(X_train)

accuracy_tree_classifier = classification_report(y_train, y_pred_tree_test)
print(accuracy_tree_classifier)

from sklearn.neighbors import KNeighborsClassifier
neighborsModel = KNeighborsClassifier(n_neighbors=3)
neighborsModel.fit(X_train, y_train)
y_pred_neighbors_model_test = neighborsModel.predict(X_test)

print(classification_report(y_test, y_pred_neighbors_model_test))



y_pred_neighbors_model_train = neighborsModel.predict(X_train)
print(classification_report(y_train, y_pred_neighbors_model_train))

from sklearn.tree import DecisionTreeClassifier

treeM = DecisionTreeClassifier(max_depth = 10)
treeM.fit(X_train, y_train)


y_pred_tree_regressor = treeM.predict(X_test)
accuracy_tree_regressor = classification_report(y_test, y_pred_tree_regressor)
print(accuracy_tree_regressor)

y_pred_tree_regressor = treeM.predict(X_train)
accuracy_tree_regressor = classification_report(y_train, y_pred_tree_regressor)
print(accuracy_tree_regressor)

sum_predictions = accuracy_score(y_pred_random_tree_test, y_test) + accuracy_score(y_pred_mlp_model_test, y_test) + accuracy_score(y_pred_tree_test, y_test) + accuracy_score(y_pred_neighbors_model_test, y_test)

random_tree_weight = accuracy_score(y_pred_random_tree_test, y_test) / sum_predictions
mlp_model_weight = accuracy_score(y_pred_mlp_model_test, y_test) / sum_predictions
classifier_tree_weight = accuracy_score(y_pred_tree_test, y_test) / sum_predictions
neighbors_model_weight = accuracy_score(y_pred_neighbors_model_test, y_test) / sum_predictions


weighted_combined_classifier_prediction_test = (y_pred_random_tree_test * random_tree_weight) + (y_pred_mlp_model_test * mlp_model_weight) + (y_pred_tree_test * classifier_tree_weight) + (y_pred_neighbors_model_test * neighbors_model_weight)

(y_pred_random_tree_test + y_pred_mlp_model_test + y_pred_tree_test + y_pred_neighbors_model_test) / 4

for i in range(len(X_test)):
  if(weighted_combined_classifier_prediction_test[i] >= 0.5):
      weighted_combined_classifier_prediction_test[i] = 1
  else:
     weighted_combined_classifier_prediction_test[i] = 0

accuracy_weighted_combined_predictions = classification_report(y_test, weighted_combined_classifier_prediction_test)
print(accuracy_weighted_combined_predictions)

w_random_tree = 1
w_mlp_model = 1
w_classifier_tree = 1
w_neighbors_model = 1

weighted_list = [0]*len(X_test)



for i in range(len(X_test)):
  combined_prediction = (y_pred_random_tree_test[i] * w_random_tree + y_pred_mlp_model_test[i] * w_mlp_model + y_pred_tree_test[i] * w_classifier_tree + y_pred_neighbors_model_test[i] * w_neighbors_model) / (w_random_tree + w_mlp_model + w_classifier_tree + w_neighbors_model)
  if(combined_prediction >= 0.5):
    combined_prediction = 1
  else:
    combined_prediction = 0
  weighted_list[i] = combined_prediction

combined_accuracy = classification_report(weighted_list, y_test)
print(combined_accuracy)